### ISSUE TITLE
yaml file with negative values

### ISSUE THREAD

**Issue by odiazib** [eagles-project/skywalker#33]
Skywalker does not correctly finish a test with the following yaml input file:

```
mam4xx:
  function: hetero
input:
  enumerated:
    Ns: [[0.0009478315467], [0.0008633937165], [0.01542388755]]
    Temperature: [[-32.69480152], [-31.94781043], [-35.75495987]]
    dt: [0.0, 0.0, 0.0]
    w_vlc: [[0.2], [0.2], [0.2]]
```

The issue with this yaml file is the negative value in the third item in the Temperature variable.
 
Skywalker works fine if I use four/two samples or if the values of the third item an input with 3 samples is positive.
